### ISSUE TITLE
PipeBlocker causing my modpack to crash on startup! ( java.lang.reflect.InvocationTargetException)

### ISSUE THREAD

**Issue by JamboTheJoyful** [Minecraft-Malware-Prevention-Alliance/PipeBlocker#20]
So first id like to clarify a few things, I Just got eclipse, and I have never used an IDE before. My goal is to resolve the issue by learning how to use eclipse; if anyone knows where I can get a good tutorial, please refer me. 
I need to learn how to even access this information in eclipse before I can try to fix it RIP.

I am currently making a modpack for a few friends and I wanted to install PipeBlocker for security. After installing PipeBlocker for 1.12.2 my game would crash on startup after launching before mod loading started. if anyone can figure out what is causing this that would be highly appreciated! 

My best guess cause is a compatibility issue with one of my mods.

If you need more information from me to solve this please ask for it!

Below is the crash log I get when I startup

Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at C:\Users\mrmcd\curseforge\minecraft\Instances\Minecraft, But Hell No for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42)
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at info.mmpa.pipeblocker.ObjectStreamFilter.apply(ObjectStreamFilter.java:162)
	at info.mmpa.pipeblocker.PipeLoadingPlugin.<init>(PipeLoadingPlugin.java:15)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:594)
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451)
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107)
	... 5 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at info.mmpa.pipeblocker.ObjectStreamFilter.apply(ObjectStreamFilter.java:159)
	... 15 more
Caused by: java.lang.NoClassDefFoundError: sun/misc/ObjectInputFilter$FilterInfo
	at info.mmpa.pipeblocker.java8.FilterSetter.apply(FilterSetter.java:8)
	... 20 more
Caused by: java.lang.ClassNotFoundException: sun.misc.ObjectInputFilter$FilterInfo
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more

**Comment by JamboTheJoyful** [comment]
this issue is the same as https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/issues/21
